version: "3.8"

services:
  registry:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DHARA_REGISTRY_STORAGE_DIR=/data
    volumes:
      - registry_data:/data

volumes:
  registry_data:
