# These are supported funding model platforms

github: [zosmaai]
# patreon: # coming soon
# open_collective: # coming soon
# ko_fi: # coming soon
# tidelift: # coming soon
# community_bridge: # coming soon
# liberapay: # coming soon
# issuehunt: # coming soon
# otechie: # coming soon
# custom: # coming soon
